server:
    port: 8761
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
        waitTimeInMsWhenSyncEmpty: 0
    instance:
        metadataMap:
            instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
